import {
  PRATEAddress,
  COWTIPAddress,
  PBONDAddress,
  WPLS,
  USDC,
  USDT,
  DAI,
  eWBTC,
  pWBTC,
  eHEX,
  pHEX,
  eWETH,
  pWETH,
  PLSX,
  INC,
  PLS_USDC_LP_Address,
  PRATE_PLS_LP_Address,
  COWTIP_PLS_LP_Address,
  PRATE_PSHARE_LP_Address,
  PRATE_USDC_LP_Address,
  PSHARE_USDC_LP_Address,
  PLS_eWBTC_LP_Address,
  PLS_pWBTC_LP_Address,
  PRATE_eWBTC_LP_Address,
  PRATE_pWBTC_LP_Address,
  PSHARE_eWBTC_LP_Address,
  PSHARE_pWBTC_LP_Address,
  PLS_eHEX_LP_Address,
  PLS_pHEX_LP_Address,
  PRATE_eHEX_LP_Address,
  PRATE_pHEX_LP_Address,
  PSHARE_eHEX_LP_Address,
  PSHARE_pHEX_LP_Address,
  PLS_eWETH_LP_Address,
  PLS_pWETH_LP_Address,
  PRATE_eWETH_LP_Address,
  PRATE_pWETH_LP_Address,
  PSHARE_eWETH_LP_Address,
  PSHARE_pWETH_LP_Address,
  PLS_PLSX_LP_Address,
  PRATE_PLSX_LP_Address,
  PSHARE_PLSX_LP_Address,
  PLS_INC_LP_Address,
  PRATE_INC_LP_Address,
  PSHARE_INC_LP_Address,
  PLS_pDAI_LP_Address,
  PRATE_pDAI_LP_Address,
  PSHARE_pDAI_LP_Address,
  pDAI,
  RH404,
  PLS_USDT_LP_Address,
  PLS_DAI_LP_Address,
  PLS_WETH_LP_Address,
  GOAT_COWTIP_LP_Address,
  PLS_pDRIP_LP_Address,
  pDRIP,
  GOAT,
  DAI_USDT_LP_Address,
  COWTIP_ETH_LP_Address,
  PLS_WDRIP_LP_Address,
  COWTIP_WDRIP_LP_Address,
  LP_COWTIP_pDAI,
  LP_RH_COWTIP,
  WDRIP,
  BITCOIN,
  ETHEREUM,
  SOL,
  BASE,
  SONIC
} from "./ContractAddresses";

export const AddressZero = "0x0000000000000000000000000000000000000000";

export const tokens = {
  [SONIC]: {
    symbol: "SONIC",
    logo: "/sonic.png",
    swap: true,
    address: SONIC,
    decimals: 18,
    format: "0,0",
  },
  [BITCOIN]: {
    symbol: "BITCOIN",
    logo: "/bitcoin.png",
    swap: true,
    address: BITCOIN,
    decimals: 8,
    format: "0,0.[000000]",
  },
  [ETHEREUM]: {
    symbol: "ETHEREUM",
    logo: "/ethereum.png",
    swap: true,
    address: ETHEREUM,
    decimals: 18,
    format: "0,0",
  },
  [SOL]: {
    symbol: "SOL",
    logo: "/sol.png",
    swap: true,
    address: SOL,
    decimals: 9,
    format: "0,0.[000000]",
  },
  [BASE]: {
    symbol: "BASE",
    logo: "/base.png",
    swap: true,
    address: BASE,
    decimals: 18,
    format: "0,0",
  },
  [PRATEAddress]: {
    symbol: "PRATE",
    logo: "/pshareforcircle.png",
    swap: true,
    address: PRATEAddress,
    decimals: 18,
    format: "0,0",
  },
  [COWTIPAddress]: {
    symbol: "COWTIP",
    logo: "/pshareforcircle.png",
    swap: true,
    address: COWTIPAddress,
    decimals: 18,
    format: "0,0.[0000]",
  },
  [PBONDAddress]: {
    symbol: "PBOND",
    logo: "/pbond.png",
    address: PBONDAddress,
    decimals: 18,
    format: "0,0",
  },
  [WPLS]: {
    symbol: "WPLS",
    logo: "/wpls.png",
    swap: true,
    address: WPLS,
    decimals: 18,
    format: "0,0",
  },
  [USDC]: {
    symbol: "USDC",
    logo: "/usdc.png",
    swap: true,
    address: USDC,
    decimals: 6,
    format: "0,0.[00]",
  },
  [eWBTC]: {
    symbol: "eWBTC",
    logo: "/ewbtc.png",
    swap: true,
    address: eWBTC,
    decimals: 8,
    format: "0,0.[000000]",
  },
  [DAI]: {
    symbol: "DAI",
    logo: "/dai.png",
    swap: true,
    address: DAI,
    decimals: 18,
    format: "0,0.[000000]",
  },
  [USDT]: {
    symbol: "USDT",
    logo: "/usdt.png",
    swap: true,
    address: USDT,
    decimals: 6,
    format: "0,0.[000000]",
  },
  [pWBTC]: {
    symbol: "pWBTC",
    logo: "/pwbtc.png",
    swap: true,
    address: pWBTC,
    decimals: 8,
    format: "0,0.[000000]",
  },
  [eHEX]: {
    symbol: "eHEX",
    logo: "/ehex.png",
    swap: true,
    address: eHEX,
    decimals: 8,
    format: "0,0.[0000]",
  },
  [pHEX]: {
    symbol: "pHEX",
    logo: "/phex.png",
    swap: true,
    address: pHEX,
    decimals: 8,
    format: "0,0.[0000]",
  },
  [eWETH]: {
    symbol: "eWETH",
    logo: "/eweth.png",
    swap: true,
    address: eWETH,
    decimals: 18,
    format: "0,0.[0000]",
  },
  [pWETH]: {
    symbol: "pWETH",
    logo: "/pweth.png",
    swap: true,
    address: pWETH,
    decimals: 18,
    format: "0,0",
  },
  [PLSX]: {
    symbol: "PLSX",
    logo: "/plsx.png",
    swap: true,
    address: PLSX,
    decimals: 18,
    format: "0,0",
  },
  [INC]: {
    symbol: "INC",
    logo: "/inc.png",
    swap: true,
    address: INC,
    decimals: 18,
    format: "0,0.[0000]",
  },
  [pDRIP]: {
    symbol: "pDRIP",
    logo: "/pdrip.png",
    swap: true,
    address: pDRIP,
    decimals: 18,
    format: "0,0",
  },
  [WDRIP]: {
    symbol: "WDRIP",
    logo: "/wdrip.png",
    swap: true,
    address: WDRIP,
    decimals: 18,
    format: "0,0",
  },
  [GOAT]: {
    symbol: "GOAT",
    logo: "/goat.png",
    swap: true,
    address: GOAT,
    decimals: 18,
    format: "0,0",
  },
  [RH404]: {
    symbol: "RH404",
    logo: "/RH404.png",
    swap: true,
    address: RH404,
    decimals: 18,
    format: "0,0",
  },
  [pDAI]: {
    symbol: "pDAI",
    logo: "/pdai.png",
    swap: true,
    address: pDAI,
    decimals: 18,
    format: "0,0",
  },
  [AddressZero]: {
    symbol: "PLS",
    logo: "/wpls.png",
    swap: true,
    address: AddressZero,
    decimals: 18,
    format: "0,0",
  },
  [COWTIP_WDRIP_LP_Address]: {
    symbol: "COWTIP-WDRIP LP",
    exchange: "- PulseX V2",
    address: COWTIP_WDRIP_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V2/0x90732c0aBC7b44F6e00c4CC90d29293D1DD01d8B/0x7e9d3C1b3619BC26D13f2c73034ACdeb6de3b42C",
  },
  [LP_COWTIP_pDAI]: {
    symbol: "COWTIP-pDAI LP",
    exchange: "- PulseX V2",
    address: LP_COWTIP_pDAI,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V2/0x90732c0aBC7b44F6e00c4CC90d29293D1DD01d8B/0x6B175474E89094C44Da98b954EedeAC495271d0F",
  },
  [LP_RH_COWTIP]: {
    symbol: "RH404-COWTIP LP",
    exchange: "- PulseX V2",
    address: LP_RH_COWTIP,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V2/0x90732c0aBC7b44F6e00c4CC90d29293D1DD01d8B/0x749ccf4c4308490F3c395De897F58e091090B461",
  },
  [PLS_WDRIP_LP_Address]: {
    symbol: "PLS-WDRIP LP",
    exchange: "- PulseX V2",
    address: PLS_WDRIP_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V2/PLS/0x7e9d3C1b3619BC26D13f2c73034ACdeb6de3b42C",
  },

  [PLS_pDRIP_LP_Address]: {
    symbol: "PLS-pDRIP LP",
    exchange: "- PulseX V2",
    address: PLS_pDRIP_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V2/PLS/0xeB2CEed77147893Ba8B250c796c2d4EF02a72B68",
  },
  [GOAT_COWTIP_LP_Address]: {
    symbol: "GOAT-COWTIP LP",
    exchange: "- PulseX V2",
    address: GOAT_COWTIP_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V2/0x90732c0aBC7b44F6e00c4CC90d29293D1DD01d8B/0xF5D0140B4d53c9476DC1488BC6d8597d7393f074",
  },
  [PLS_USDC_LP_Address]: {
    symbol: "PLS-USDC LP",
    exchange: "- PulseX V1",
    address: PLS_USDC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V1/PLS/0x15D38573d2feeb82e7ad5187aB8c1D52810B1f07",
  },
  [PLS_USDT_LP_Address]: {
    symbol: "PLS-USDT LP",
    exchange: "- PulseX V1",
    address: PLS_USDT_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V1/PLS/0x0Cb6F5a34ad42ec934882A05265A7d5F59b51A2f",
  },
  [PLS_DAI_LP_Address]: {
    symbol: "PLS-DAI LP",
    exchange: "- PulseX V1",
    address: PLS_DAI_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V1/PLS/0xefD766cCb38EaF1dfd701853BFCe31359239F305",
  },
  [PRATE_PLS_LP_Address]: {
    symbol: "PRATE-WPLS LP",
    address: PRATE_PLS_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [COWTIP_PLS_LP_Address]: {
    symbol: "COWTIP-PLS LP ",
    exchange: "- PulseX V2",
    address: COWTIP_PLS_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V2/PLS/0x90732c0aBC7b44F6e00c4CC90d29293D1DD01d8B",
  },
  [COWTIP_ETH_LP_Address]: {
    symbol: "COWTIP-ETH LP ",
    exchange: "- PulseX V2",
    address: COWTIP_ETH_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V2/0x02DcdD04e3F455D838cd1249292C58f3B79e3C3C/0x90732c0aBC7b44F6e00c4CC90d29293D1DD01d8B",
  },
  [DAI_USDT_LP_Address]: {
    symbol: "DAI-USDT LP ",
    exchange: "- PulseX V2",
    address: DAI_USDT_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V2/0xefD766cCb38EaF1dfd701853BFCe31359239F305/0x0Cb6F5a34ad42ec934882A05265A7d5F59b51A2f",
  },
  [PRATE_PSHARE_LP_Address]: {
    symbol: "PRATE-PSHARE LP",
    address: PRATE_PSHARE_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PRATE_USDC_LP_Address]: {
    symbol: "PRATE-USDC LP",
    address: PRATE_USDC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },

  [PSHARE_USDC_LP_Address]: {
    symbol: "PSHARE-USDC LP",
    address: PSHARE_USDC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PLS_eWBTC_LP_Address]: {
    symbol: "WPLS-eWBTC LP",
    address: PLS_eWBTC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PLS_pWBTC_LP_Address]: {
    symbol: "WPLS-pWBTC LP",
    address: PLS_pWBTC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PRATE_eWBTC_LP_Address]: {
    symbol: "PRATE-eWBTC LP",
    address: PRATE_eWBTC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PRATE_pWBTC_LP_Address]: {
    symbol: "PRATE-pWBTC LP",
    address: PRATE_pWBTC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PSHARE_eWBTC_LP_Address]: {
    symbol: "PSHARE-eWBTC LP",
    address: PSHARE_eWBTC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PSHARE_pWBTC_LP_Address]: {
    symbol: "PSHARE-pWBTC LP",
    address: PSHARE_pWBTC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PLS_eHEX_LP_Address]: {
    symbol: "WPLS-eHEX LP",
    address: PLS_eHEX_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PLS_pHEX_LP_Address]: {
    symbol: "WPLS-pHEX LP",
    address: PLS_pHEX_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PRATE_eHEX_LP_Address]: {
    symbol: "PRATE-eHEX LP",
    address: PRATE_eHEX_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PRATE_pHEX_LP_Address]: {
    symbol: "PRATE-pHEX LP",
    address: PRATE_pHEX_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PSHARE_eHEX_LP_Address]: {
    symbol: "PSHARE-eHEX LP",
    address: PSHARE_eHEX_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PSHARE_pHEX_LP_Address]: {
    symbol: "PSHARE-pHEX LP",
    address: PSHARE_pHEX_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PLS_eWETH_LP_Address]: {
    symbol: "WPLS-eWETH LP",
    address: PLS_eWETH_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PLS_pWETH_LP_Address]: {
    symbol: "WPLS-pWETH LP",
    address: PLS_pWETH_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PRATE_eWETH_LP_Address]: {
    symbol: "PRATE-eWETH LP",
    address: PRATE_eWETH_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PRATE_pWETH_LP_Address]: {
    symbol: "PRATE-pWETH LP",
    address: PRATE_pWETH_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PSHARE_eWETH_LP_Address]: {
    symbol: "PSHARE-eWETH LP",
    address: PSHARE_eWETH_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PSHARE_pWETH_LP_Address]: {
    symbol: "PSHARE-pWETH LP",
    address: PSHARE_pWETH_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PLS_PLSX_LP_Address]: {
    symbol: "PLS-PLSX LP",
    address: PLS_PLSX_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PRATE_PLSX_LP_Address]: {
    symbol: "PRATE-PLSX LP",
    address: PRATE_PLSX_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PSHARE_PLSX_LP_Address]: {
    symbol: "PSHARE-PLSX LP",
    address: PSHARE_PLSX_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PLS_INC_LP_Address]: {
    symbol: "PLS-INC LP",
    exchange: " - PulseX V1",
    address: PLS_INC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V1/PLS/0x2fa878Ab3F87CC1C9737Fc071108F904c0B0C95d",
  },
  [PLS_WETH_LP_Address]: {
    symbol: "PLS-WETH LP",
    exchange: " - PulseX V1",
    address: PLS_WETH_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
    addLiquidityLink: "https://pulsex.mypinata.cloud/ipfs/bafybeidea3ibq4lu5t6vk6ihp4iuznjb3ltsdm5y2shv4atxgyd3d33aim/#/add/V1/PLS/0x02DcdD04e3F455D838cd1249292C58f3B79e3C3C",
  },
  [PRATE_INC_LP_Address]: {
    symbol: "PRATE-INC LP",
    address: PRATE_INC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PSHARE_INC_LP_Address]: {
    symbol: "PSHARE-INC LP",
    address: PSHARE_INC_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PLS_pDAI_LP_Address]: {
    symbol: "PLS-pDAI LP",
    address: PLS_pDAI_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PRATE_pDAI_LP_Address]: {
    symbol: "PRATE-pDAI LP",
    address: PRATE_pDAI_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
  [PSHARE_pDAI_LP_Address]: {
    symbol: "PSHARE-pDAI LP",
    address: PSHARE_pDAI_LP_Address,
    decimals: 18,
    liquidity: true,
    format: "0,0.[000000]",
  },
};

export const casinoTokens = {
  [AddressZero]: {
    symbol: "PLS",
    logo: "/wpls.png",
    swap: true,
    address: AddressZero,
    decimals: 18,
    format: "0,0",
  },
  [PRATEAddress]: {
    symbol: "PRATE",
    logo: "/prate.png",
    swap: true,
    address: PRATEAddress,
    decimals: 18,
    format: "0,0",
  },
  [COWTIPAddress]: {
    symbol: "PSHARE",
    logo: "/pshare.png",
    swap: true,
    address: COWTIPAddress,
    decimals: 18,
    format: "0,0.[0000]",
  },
};
